apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app01
  namespace: argocd
spec:
  destination:
    namespace: app01
    server: https://kubernetes.default.svc
  source:
    path: 291_gitops_argocd_helm/helm
    repoURL: https://github.com/HoussemDellai/aks-course
    targetRevision: HEAD
  project: project-apps