name: Check Markdown Quality

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  spell-ckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: streetsidesoftware/cspell-action@v3
        name: Spell Check
        with:
          github_token: ${{ github.token }}
          config: './.vscode/cspell.json'
          inline: warning
          root: '.'
          files: |
            **/*.md
            !dist/**/*.{ts,js}
          # Limit the files checked to the ones in the pull request or push.
          incremental_files_only: true
          strict: true #setting to false allows the build to continue even if spelling mistakes are detected
