name: Check Spell Markdown

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  spell-ckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: streetsidesoftware/cspell-action@v3
        name: Spell Check
        continue-on-error: true
        with:
          github_token: ${{ github.token }}
          config: './.spell_check/cspell.json'
          inline: warning
          root: '.'
          files: |
            **/*.md
            !dist/**/*.{ts,js}
          # Limit the files checked to the ones in the pull request or push.
          incremental_files_only: true
          strict: true #setting to false allows the build to continue even if spelling mistakes are detected

      - uses: rojopolis/spellcheck-github-actions@v0
        name: Spellcheck
        with:
          # source_files: "**/*.md"
          task_name: Markdown
          config_path: .spell_check/.spellcheck.yaml
